// <auto-generated />
using System;
using App.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("App.Domain.Models.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "qwer"
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("AppointmentCost")
                        .HasColumnType("REAL");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("NurseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("varchar(32)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("NurseId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RoomId");

                    b.ToTable("Appointment");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentCost = 120f,
                            DoctorId = 1,
                            EndTime = new DateTime(2022, 1, 1, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            NurseId = 3,
                            PatientId = 5,
                            RoomId = 1,
                            StartTime = new DateTime(2022, 1, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentCost = 100f,
                            DoctorId = 2,
                            EndTime = new DateTime(2023, 5, 7, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            NurseId = 4,
                            PatientId = 6,
                            RoomId = 2,
                            StartTime = new DateTime(2023, 5, 7, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentCost = 100f,
                            DoctorId = 2,
                            EndTime = new DateTime(2023, 5, 7, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            NurseId = 4,
                            PatientId = 5,
                            RoomId = 2,
                            StartTime = new DateTime(2023, 5, 7, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Certification", b =>
                {
                    b.Property<int>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CertificationId");

                    b.ToTable("Certification");

                    b.HasData(
                        new
                        {
                            CertificationId = 1,
                            Title = "any title"
                        },
                        new
                        {
                            CertificationId = 2,
                            Title = "any title"
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDiagnosed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("DiagnosisId");

                    b.ToTable("Diagnosis");

                    b.HasData(
                        new
                        {
                            DiagnosisId = 1,
                            DateDiagnosed = new DateTime(2022, 1, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kemo"
                        },
                        new
                        {
                            DiagnosisId = 2,
                            DateDiagnosed = new DateTime(2022, 1, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "ECG"
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Doctor_Specialization", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DoctorId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctor_Specialization");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 2,
                            SpecializationId = 2
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("PricePerProcedure")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1,
                            PricePerProcedure = 100.99f,
                            Title = "Surgery"
                        },
                        new
                        {
                            EquipmentId = 2,
                            PricePerProcedure = 80.99f,
                            Title = "PostMortem"
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Examination", b =>
                {
                    b.Property<int>("ExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExaminationTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExaminationId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("ExaminationTypeId");

                    b.ToTable("Examination");

                    b.HasData(
                        new
                        {
                            ExaminationId = 1,
                            AppointmentId = 1,
                            ExaminationTypeId = 1
                        },
                        new
                        {
                            ExaminationId = 2,
                            AppointmentId = 2,
                            ExaminationTypeId = 2
                        });
                });

            modelBuilder.Entity("App.Domain.Models.ExaminationType", b =>
                {
                    b.Property<int>("ExaminationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ExaminationTypeId");

                    b.ToTable("ExaminationType");

                    b.HasData(
                        new
                        {
                            ExaminationTypeId = 1,
                            Title = "Full"
                        },
                        new
                        {
                            ExaminationTypeId = 2,
                            Title = "Partial"
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Examination_Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExaminationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiagnosisId", "ExaminationId");

                    b.HasIndex("ExaminationId");

                    b.ToTable("Examination_Diagnosis");

                    b.HasData(
                        new
                        {
                            DiagnosisId = 1,
                            ExaminationId = 1
                        },
                        new
                        {
                            DiagnosisId = 2,
                            ExaminationId = 2
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineType")
                        .HasColumnType("varchar(32)");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicineId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("Medicine");

                    b.HasData(
                        new
                        {
                            MedicineId = 1,
                            Amount = 10,
                            MedicineType = 0,
                            ProcedureId = 1
                        },
                        new
                        {
                            MedicineId = 2,
                            Amount = 5,
                            MedicineType = 1,
                            ProcedureId = 2
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Nurse_Certification", b =>
                {
                    b.Property<int>("NurseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CertificationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NurseId", "CertificationId");

                    b.HasIndex("CertificationId");

                    b.ToTable("Nurse_Certification");

                    b.HasData(
                        new
                        {
                            NurseId = 3,
                            CertificationId = 1
                        },
                        new
                        {
                            NurseId = 4,
                            CertificationId = 1
                        },
                        new
                        {
                            NurseId = 4,
                            CertificationId = 2
                        });
                });

            modelBuilder.Entity("App.Domain.Models.PatientAllergy", b =>
                {
                    b.Property<int>("AllergyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AllergyId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatientPersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AllergyId", "PatientId");

                    b.HasIndex("AllergyId1");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientPersonId");

                    b.ToTable("PatientAllergy", (string)null);

                    b.HasData(
                        new
                        {
                            AllergyId = 1,
                            PatientId = 5
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("App.Domain.Models.Procedure", b =>
                {
                    b.Property<int>("ProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MedicineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcedureTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProcedureId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("MedicineId");

                    b.HasIndex("ProcedureTypeId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("Procedure");

                    b.HasData(
                        new
                        {
                            ProcedureId = 1,
                            AppointmentId = 1,
                            ProcedureTypeId = 1,
                            TreatmentId = 1
                        },
                        new
                        {
                            ProcedureId = 2,
                            AppointmentId = 2,
                            ProcedureTypeId = 2,
                            TreatmentId = 2
                        });
                });

            modelBuilder.Entity("App.Domain.Models.ProcedureType", b =>
                {
                    b.Property<int>("ProcedureTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ProcedureTypeId");

                    b.ToTable("ProcedureType");

                    b.HasData(
                        new
                        {
                            ProcedureTypeId = 1,
                            Title = "Dont Know"
                        },
                        new
                        {
                            ProcedureTypeId = 2,
                            Title = "Dont Care"
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Procedure_Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EquipmentId", "ProcedureId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("Procedure_Equipment");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1,
                            ProcedureId = 1
                        },
                        new
                        {
                            EquipmentId = 2,
                            ProcedureId = 2
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("RoomId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            RoomNumber = "1230A"
                        },
                        new
                        {
                            RoomId = 2,
                            RoomNumber = "1234D"
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specialization");

                    b.HasData(
                        new
                        {
                            SpecializationId = 1,
                            Title = "Dentistry"
                        },
                        new
                        {
                            SpecializationId = 2,
                            Title = "Cardiology"
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Treatment", b =>
                {
                    b.Property<int>("TreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TreatmentId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("Treatment");

                    b.HasData(
                        new
                        {
                            TreatmentId = 1,
                            DiagnosisId = 1,
                            Title = "Main"
                        },
                        new
                        {
                            TreatmentId = 2,
                            DiagnosisId = 2,
                            Title = "Secondry"
                        });
                });

            modelBuilder.Entity("App.Domain.Models.MedicalStaff", b =>
                {
                    b.HasBaseType("App.Domain.Models.Person");

                    b.Property<float>("MonthlySalary")
                        .HasColumnType("REAL");

                    b.Property<float>("RatePerHour")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("MedicalStaff");
                });

            modelBuilder.Entity("App.Domain.Models.Patient", b =>
                {
                    b.HasBaseType("App.Domain.Models.Person");

                    b.Property<long>("InsuranceNumber")
                        .HasColumnType("INTEGER");

                    b.HasIndex("InsuranceNumber")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Patient");

                    b.HasData(
                        new
                        {
                            PersonId = 5,
                            DateOfBirth = new DateTime(2002, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Victor",
                            Gender = 0,
                            LastName = "Stone",
                            InsuranceNumber = 12365478L
                        },
                        new
                        {
                            PersonId = 6,
                            DateOfBirth = new DateTime(2002, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Arthur",
                            Gender = 1,
                            LastName = "Curry",
                            InsuranceNumber = 12365008L
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Doctor", b =>
                {
                    b.HasBaseType("App.Domain.Models.MedicalStaff");

                    b.Property<float>("BonusPerAppointment")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Doctor");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bruce",
                            Gender = 0,
                            LastName = "Wayne",
                            MonthlySalary = 16000f,
                            RatePerHour = 100f,
                            BonusPerAppointment = 10f
                        },
                        new
                        {
                            PersonId = 2,
                            DateOfBirth = new DateTime(1999, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Clark",
                            Gender = 0,
                            LastName = "Kent",
                            MonthlySalary = 24158.4f,
                            RatePerHour = 150.99f,
                            BonusPerAppointment = 0f
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Nurse", b =>
                {
                    b.HasBaseType("App.Domain.Models.MedicalStaff");

                    b.HasDiscriminator().HasValue("Nurse");

                    b.HasData(
                        new
                        {
                            PersonId = 3,
                            DateOfBirth = new DateTime(1998, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dianna",
                            Gender = 1,
                            LastName = "Price",
                            MonthlySalary = 14558.399f,
                            RatePerHour = 90.99f
                        },
                        new
                        {
                            PersonId = 4,
                            DateOfBirth = new DateTime(1998, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Barry",
                            Gender = 0,
                            LastName = "Allen",
                            MonthlySalary = 14558.399f,
                            RatePerHour = 90.99f
                        });
                });

            modelBuilder.Entity("App.Domain.Models.Appointment", b =>
                {
                    b.HasOne("App.Domain.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Nurse", "Nurse")
                        .WithMany("Appointments")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Room", "Room")
                        .WithMany("Appointments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("App.Domain.Models.Doctor_Specialization", b =>
                {
                    b.HasOne("App.Domain.Models.Doctor", "Doctor")
                        .WithMany("Doctor_Specializations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Specialization", "Specialization")
                        .WithMany("Doctor_Specializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("App.Domain.Models.Examination", b =>
                {
                    b.HasOne("App.Domain.Models.Appointment", "Appointment")
                        .WithOne("Examination")
                        .HasForeignKey("App.Domain.Models.Examination", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.ExaminationType", "ExaminationType")
                        .WithMany("Examinations")
                        .HasForeignKey("ExaminationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ExaminationType");
                });

            modelBuilder.Entity("App.Domain.Models.Examination_Diagnosis", b =>
                {
                    b.HasOne("App.Domain.Models.Diagnosis", "Diagnosis")
                        .WithMany("Examination_Diagnoses")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Examination", "Examination")
                        .WithMany("Examination_Diagnoses")
                        .HasForeignKey("ExaminationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");

                    b.Navigation("Examination");
                });

            modelBuilder.Entity("App.Domain.Models.Medicine", b =>
                {
                    b.HasOne("App.Domain.Models.Procedure", "Procedure")
                        .WithMany("Medicines")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("App.Domain.Models.Nurse_Certification", b =>
                {
                    b.HasOne("App.Domain.Models.Certification", "Certification")
                        .WithMany("Nurse_Certifications")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Nurse", "Nurse")
                        .WithMany("Nurse_Certifications")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("App.Domain.Models.PatientAllergy", b =>
                {
                    b.HasOne("App.Domain.Models.Allergy", null)
                        .WithMany()
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Allergy", "Allergy")
                        .WithMany()
                        .HasForeignKey("AllergyId1");

                    b.HasOne("App.Domain.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientPersonId");

                    b.Navigation("Allergy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("App.Domain.Models.Procedure", b =>
                {
                    b.HasOne("App.Domain.Models.Appointment", "Appointment")
                        .WithOne("Procedure")
                        .HasForeignKey("App.Domain.Models.Procedure", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Medicine", null)
                        .WithMany("Procedures")
                        .HasForeignKey("MedicineId");

                    b.HasOne("App.Domain.Models.ProcedureType", "ProcedureType")
                        .WithMany("Procedures")
                        .HasForeignKey("ProcedureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Treatment", "Treatment")
                        .WithMany("procedures")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ProcedureType");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("App.Domain.Models.Procedure_Equipment", b =>
                {
                    b.HasOne("App.Domain.Models.Equipment", "Equipment")
                        .WithMany("Procedure_Equipment")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Models.Procedure", "Procedure")
                        .WithMany("Procedure_Equipment")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("App.Domain.Models.Treatment", b =>
                {
                    b.HasOne("App.Domain.Models.Diagnosis", "Diagnosis")
                        .WithMany("Treatments")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("App.Domain.Models.Appointment", b =>
                {
                    b.Navigation("Examination");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("App.Domain.Models.Certification", b =>
                {
                    b.Navigation("Nurse_Certifications");
                });

            modelBuilder.Entity("App.Domain.Models.Diagnosis", b =>
                {
                    b.Navigation("Examination_Diagnoses");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("App.Domain.Models.Equipment", b =>
                {
                    b.Navigation("Procedure_Equipment");
                });

            modelBuilder.Entity("App.Domain.Models.Examination", b =>
                {
                    b.Navigation("Examination_Diagnoses");
                });

            modelBuilder.Entity("App.Domain.Models.ExaminationType", b =>
                {
                    b.Navigation("Examinations");
                });

            modelBuilder.Entity("App.Domain.Models.Medicine", b =>
                {
                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("App.Domain.Models.Procedure", b =>
                {
                    b.Navigation("Medicines");

                    b.Navigation("Procedure_Equipment");
                });

            modelBuilder.Entity("App.Domain.Models.ProcedureType", b =>
                {
                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("App.Domain.Models.Room", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("App.Domain.Models.Specialization", b =>
                {
                    b.Navigation("Doctor_Specializations");
                });

            modelBuilder.Entity("App.Domain.Models.Treatment", b =>
                {
                    b.Navigation("procedures");
                });

            modelBuilder.Entity("App.Domain.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("App.Domain.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Doctor_Specializations");
                });

            modelBuilder.Entity("App.Domain.Models.Nurse", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Nurse_Certifications");
                });
#pragma warning restore 612, 618
        }
    }
}
